
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZStudent = z.object({
      "studentName": z.string(),
      "ID": z.string(),
      "currentGrade": z.string(),
      "currentStatus": z.string(),
      "graduationDate": z.string(),
      "PERSON::gender": z.string(),
      "PERSON::ethnicity": z.string(),
      "PERSON::dateofbirth": z.string(),
      "PERSON::race": z.string(),
      "PARTY::dEmail": z.string(),
      "PARTY::dParentEmails": z.string(),
      "PARTY::JSON_partyHH1Address": z.string(),
      "CONTACT::HomePhone": z.string(),
      "CONTACT::WorkPhone": z.string(),
      "CONTACT::MobilePhone": z.string(),
      "CONTACT::Religion": z.string(),
      "PERSON::height": z.string(),
  });

  export type TStudent = z.infer<typeof ZStudent>;
