
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZStudentFamilialRelationship = z.object({
      "studentName": z.string(),
      "ID": z.string(),
      "PARTY::JSON_partyHH1Address": z.string(),
      "PARTY::dParentNames": z.string(),
      "PARTY::dParentEmails": z.string(),
      "student_ext::_householdJSON": z.string(),
      "student_ext::_siblingJSON": z.string(),
  });

  export type TStudentFamilialRelationship = z.infer<typeof ZStudentFamilialRelationship>;
