
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZStudentAcademicHistory = z.object({
      "studentName": z.string(),
      "ID": z.string(),
      "studentYear::AiCourseNameJSON": z.string(),
  });

  export type TStudentAcademicHistory = z.infer<typeof ZStudentAcademicHistory>;
