
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const Zstudent = z.object({
      "__id": z.string(),
      "address": z.string(),
      "dob": z.string(),
      "email": z.string(),
      "enrollmentDate": z.string(),
      "graduationYear": z.string(),
      "nameFirst": z.string(),
      "nameLast": z.string(),
      "nameMiddle": z.string(),
      "phoneNumber": z.string(),
      "zCreatedBy": z.string(),
      "zCreationTimestamp": z.string(),
      "zModificationTimestamp": z.string(),
      "zModifiedBy": z.string(),
  });

  export type Tstudent = z.infer<typeof Zstudent>;
